### ISSUE TITLE
Webhooks

### ISSUE THREAD

**Issue by simone-torino** [mevellea/telegram_menu#11]
Hi, how would one set the bot for using webhooks instead of polling? It would be for cloud hosting purposes.
I don't have much experience with python, I tried some tweaks on the source code but i could not find a solution. Thank you for your work

**Comment by mevellea** [comment]
Hello, then I suggest that you read the documentation of Telegram bot API first: [https://core.telegram.org/bots/api](https://core.telegram.org/bots/api)

**Comment by simone-torino** [comment]
Thanks for the fast answer. Reading the documentation i get that I should need to use methods `updater.start_webhook()` and
`updater.bot.setWebhook()` (with some args) instead of `updater.start_polling()` but the problem is that this last method is called in the file navigation.py under the class TelegramMenuSession that it's not supposed to be modified. 
Is there a way to implement webhooks without modifying navigation.py? Maybe it's a common thing but I can't find a solution

**Comment by mevellea** [comment]
Ok I would propose to add an optional argument to skip the call to `start_polling`, then the client can start the updater with all the arguments needed:
```
session = TelegramMenuSession(...)
session.start(polling=False, idle=False)
session.updater.start_webhook(...)
session.updater.idle()
```
Let me know if that works for you.

**Comment by simone-torino** [comment]
It worked perfectly, thank you for your time
