### ISSUE TITLE
Unittest help: Sending manual request

### ISSUE THREAD

**Issue by Moon-developer** [mevellea/telegram_menu#12]
How do you run unittests for the current one? Do you manually send a message to the bot during the pipeline test or is there a telegram client that messages it using something like Telethon library?

I've sort of got it setup with Telethon but keep getting:
```
    last_menu_message = self._menu_queue[-1]
IndexError: list index out of range
```
from the unittest. Same thing if I message manually

**Comment by mevellea** [comment]
Hi, this is a manual unit-test, the sequence will enter polling mode and wait for any message from the test client before executing the list of actions.
If you have something working with telethon you are welcome to share it as I don't have much time to improve this package.
