### ISSUE TITLE
Fullstops and commas doesn't work in button texts

### ISSUE THREAD

**Issue by crypt0grapher** [mevellea/telegram_menu#19]
Currently, I'm using such a workaround for this, it would be great if it is possible to add more formatting options to the button texts.

```Python
 MenuButton(label="Max Eth: " + str(max_value).replace(".", "•"), callback=self.new_max_value)
```

**Comment by crypt0grapher** [comment]
And many thanks for the awesome package!

**Comment by mevellea** [comment]
Thanks for reporting, it's fixed
