### ISSUE TITLE
Feature Request: Survey button

### ISSUE THREAD

**Issue by bprashanth** [mevellea/telegram_menu#22]
Hi hello and aloha. 

Thanks for the project! Looks very useful. I have a feature request. 

I'd love for a way to get data through this menu. I mean for example: 

* User hits survey button
* Bot sends first question 
* User types first reply and hits enter 
* Bot sends second question... etc
* Quiz finished
* Bot gets callback function with answers 

Is this already possible? 
If not, can you point me at how I might upstream this functionality?

**Comment by bprashanth** [comment]
Ah I guess I can use the [bot object](https://github.com/mevellea/telegram_menu/blob/master/telegram_menu/navigation.py#L248) through the `BaseMessage` to invoke `get_updates` or something like that?

**Comment by mevellea** [comment]
Hello, all the APIs you need already exist to implement this kind of use-case, I invite you to look at `tests\demo.py`, and also read the documentation.
