### ISSUE TITLE
input text on button

### ISSUE THREAD

**Issue by novak82** [mevellea/telegram_menu#3]
Sorry, this is not a isue but a suggestion.
I would suggest that you show in the example the possibility of entering text after pressing the button. With this example the usability possibilities are much greater...

**Comment by mevellea** [comment]
Hi, yes should be possible, I will see what I can do

**Comment by novak82** [comment]
Thank you !!!
Ideally it would be to be action, and your tool could be used with easy in practice!

**Comment by mevellea** [comment]
Pushed, see example in "test_connection.py"
