### ISSUE TITLE
Can I use this library in webhook method

### ISSUE THREAD

**Issue by sid-r-singh** [mevellea/telegram_menu#4]
Hi there, I loved your work. But I have a doubt. I am using Telegram bot with web hooks. To be precise, the webhook posts update to Azure functions (which then sends a text reply to the chat).

Can I send menu buttons as well in this scenario ? Again I am not using any python libraries for sending messages I am just using requests to post data to Telegram REST API. I am attaching screenshot of  my code(which gets executed in Azure functions) for further reference.

![Screenshot from 2021-03-08 22-56-50](https://user-images.githubusercontent.com/68782815/110358114-05f49f00-8062-11eb-9c82-0278b11cf110.png)

**Comment by mevellea** [comment]
Hi, if you want to use web hooks with Python, I would recommend to use directly [python-telegram-bot](https://github.com/python-telegram-bot/python-telegram-bot) instead

**Comment by sid-r-singh** [comment]
OK. Thank you.
