### ISSUE TITLE
RuntimeError: cannot schedule new futures after interpreter shutdown

### ISSUE THREAD

**Issue by Moon-developer** [mevellea/telegram_menu#8]
The error above seems to be common with Python 3.9+ when using `python-telegram-bot`. A fix for this is to call `idle()` after `start_polling()`. Currently I override the method `start` in `TelegramMenuSession` as to include the following:

```python
class TelegramMenuSession:
    ...
    def start(self, start_messag...):
        ...
        self.updater.start_polling()
        self.updater.idle()    # New 
```
Link to [solution](https://stackoverflow.com/a/70722653/11197192)

**Comment by mevellea** [comment]
Interesting, I didn't know that feature. I will add an optional flag `idle` to keep the `start` API backward-compatible.
```
    def start(... idle: bool = False):
        ...
        self.updater.start_polling()
        if idle:
            self.updater.idle() 
```

**Comment by Moon-developer** [comment]
This seems like a good simple solution :)
