### ISSUE TITLE
User text input 

### ISSUE THREAD

**Issue by Moon-developer** [mevellea/telegram_menu#9]
Hi

How would one get the user text input? When I type something the menu goes away and can't bring it back.

**Comment by mevellea** [comment]
Hi, you can find an example of user input acquisition in the demo code, ThirdMenuMessage.text_input().
The menu will come back if you select the menu icon.

**Comment by Moon-developer** [comment]
Thank you. It took me a while to get the hang of this menu since I'm still new to telegram bots. The demo helped but I'm unsure how to clear messages sent to keep the chat clean. Maybe can we get a `Discussion` tab opened on this project instead of raising it as an issue?

**Comment by mevellea** [comment]
It's only possible to delete messages which were sent by the bot itself.
Do you mean deleting the message sent from the `text_input()` callback? This would mean adding a new method like:
```python
    def text_input(self, text: str) -> None:
        """Process text received."""
        msg_id = self.navigation.select_menu_button("Action")
        # deletion of the message from the application
        self.navigation.delete_message(message_id=msg_id)
```

**Comment by Moon-developer** [comment]
I think being able to delete both for a cleaner menu would be ideal but for now, just being able to delete the bot messages should be more than enough. I see there's a `_message_queue` in Navigation but when I try access it during runtime it seems to be empty, might be that I'm not accessing it at the correct time?

**Comment by mevellea** [comment]
The message queue contains only the messages which were sent from the menu, not from the user entries.
The method `delete_message` is in place now.

**Comment by Moon-developer** [comment]
Thank you :)
